name: Feature Request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Why?
      placeholder: How would this improve the bot for your workspace?
